# Generated by Django 4.2.5 on 2024-02-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='one_id',
        ),
        migrations.AddField(
            model_name='quest',
            name='quest_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
