# Generated by Django 4.2.5 on 2024-02-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_quest_one_id_quest_quest_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.theme'),
        ),
    ]
