# Generated by Django 4.2.5 on 2024-02-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_quest_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='app.theme'),
        ),
    ]
